FROM golang:1.25.4 AS builder

WORKDIR /workspace
COPY go.mod go.sum ./
RUN go mod download

COPY . .
WORKDIR /workspace/api-gateway/cmd/api-gateway
RUN go generate ./...

WORKDIR /workspace/api-gateway
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /bin/api-gateway ./cmd/api-gateway

FROM gcr.io/distroless/base-debian12
ENV AUTH_SERVICE_URL=http://auth-service:8081/auth
ENV TASK_SERVICE_URL=http://task-service:8082/api
ENV GATEWAY_ADDR=:8080
COPY --from=builder /bin/api-gateway /usr/local/bin/api-gateway
EXPOSE 8080
ENTRYPOINT ["/usr/local/bin/api-gateway"]
