FROM golang:1.25.4 AS builder

WORKDIR /workspace
COPY go.mod go.sum ./
RUN go mod download

COPY . .
WORKDIR /workspace/services/auth-service
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /bin/auth-service ./cmd/auth-service

FROM gcr.io/distroless/base-debian12
ENV AUTH_HTTP_ADDR=:8081
ENV DATABASE_URL=postgres://postgres:postgres@db:5432/go_micro_task_board?sslmode=disable
ENV JWT_SECRET=dev-secret
COPY --from=builder /bin/auth-service /usr/local/bin/auth-service
EXPOSE 8081
ENTRYPOINT ["/usr/local/bin/auth-service"]
